### ISSUE TITLE
create tour detail view

### ISSUE THREAD

**Issue by mattlub** [FACN1/re-discover-your-country#21]
related to #9

e.g. see http://www.nazarene-tours.com/package/rome-milan-madrid/

**Comment by HilbertSpitzer** [comment]
Mmm, Lubes. You do realize that you reference the same day below three times right? I don't think this is meanngful, I thought you were supposed to do a single event that happened in a single day, so why didn't you put different times during the day in which we would have the same trip instead of repeating الإثنين
